version: '3.8'

networks:
  shared-network:
    external: true

services:
  client:
    image: react_app
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: EN-client-web
    ports:
      - "80:80"
    networks:
      - shared-network
