accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    defaultRule: "Host({{ normalize .Name }})"

http:
  routers:
    api:
      rule: "Host(localhost)"
      service: api
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://postgres:5433"       # Master PostgreSQL