version: '3.4'

services:
  webapp:
    image: api_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5041:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmergencyAlert;User Id=sa;Password=SKFr2t_root;
      - Redis__Connection=redis:6379
      - MongoDB__Connection=mongodb://mongo:27017
    depends_on:
       - sqlserver
       - redis
       - mongo
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SKFr2t_root"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongodb/mongodb-community-server:7.0.3-ubi9
    ports:
      - "27017:27017"
